baseURL: "https://damasc-project.github.io/" 
title: DAMASC Project
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Overview
          url: overview/
          weight: 1 
        - name: Team
          url: team/
          weight: 2
        - name: Features
          url: features/
          weight: 3
#        - name: Demo
#          url: demo/
#          weight: 4
        - name: Publications
          url: publications/
          weight: 5
        - name: Contact
          url: contact/
          weight: 6

params:
    description: "DAMASC: Dynamic Analysis, Modeling and Adaptive Support for Collaborative Writing project."
    author: Jakub Kuzilek
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["overview","team","features","publications","contact"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: DAMASC Project
          subtitle: "DAMASC: Dynamic Analysis, Modeling and Adaptive Support for Collaborative Writing project aims at developing a system for analysis and support of collaborative writing at scale. It is collaborative project between the Humboldt-Universität zu Berlin and FernUniversität in Hagen."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Overview
              url: overview/
            - name: Team
              url: team/
            - name: Features
              url: features/
#           - name: Demo
#             url: demo/
            - name: Publications
              url: publications/
            - name: Contact
              url: contact/
    socialIcons:
        - name: Proposal
          url: proposal.pdf
        - name: Email
          url: mailto:jakub.kuzilek@hu-berlin.de
#        - name: Zoom
#          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
#        - name: Office Hours
#          url: officehours/
#        - name: Google Scholar
#          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
#        - name: GitHub
#          url: https://github.com/pmichaillat
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: YouTube
#          url: https://www.youtube.com/@alexandermccallsmithoffici9000
#        - name: Twitter
#          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "DAMASC Project"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
